const actionTypes = {
	GET_ITEMS: 'GET_ITEMS',
	GET_ITEMS_SUCCESS: 'GET_ITEMS_SUCCESS',
	GET_ITEMS_FAILED: 'GET_ITEMS_FAILED',

	ADD_ITEM: 'ADD_ITEM',
	ADD_ITEM_SUCCESS: 'ADD_ITEM_SUCCESS',
	ADD_ITEM_FAILED: 'ADD_ITEM_FAILED',

	REMOVE_ITEM: 'REMOVE_ITEM',
	REMOVE_ITEM_SUCCESS: 'REMOVE_ITEM_SUCCESS',
	REMOVE_ITEM_FAILED: 'REMOVE_ITEM_FAILED',
}
export default actionTypes
