const actionTypes = {
	LOGIN: 'LOGIN',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAILED: 'LOGIN_FAILED',

	LOGOUT: 'LOGOUT',
	LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
	LOGOUT_FAILED: 'LOGOUT_FAILED',

	SET_AUTH_USER: 'SET_AUTH_USER',
	SET_AUTH_USER_SUCCESS: 'SET_AUTH_USER_SUCCESS',
	SET_AUTH_USER_FAILED: 'SET_AUTH_USER_FAILED',
}
export default actionTypes
